### ISSUE TITLE
GPM (TTY-Mode) doesn't work

### ISSUE THREAD

**Issue by tobi2409** [browsh-org/browsh#402] opened 2022-02-25 22:56 UTC
It seems that it's not possible clicking HTML elements (buttons, textfields etc.) with GPM-Mouse in TTY-Mode.

**Comment by tombh** [comment] 2022-02-25 23:02
Browsh generally works with a mouse. So maybe it's a specific website, can you give an example URL where it happens?

**Comment by tobi2409** [comment] 2022-02-25 23:13
I tried it with Google, Amazon and Youtube. In KDE-Konsole I can work with mouse but in TTY-Mode and enabled GPM it's not possible.

**Comment by tombh** [comment] 2022-02-25 23:15
So Google works with the mouse in KDE's Konsole app? I don't understand why GPM is relevant here?

**Comment by tobi2409** [comment] 2022-02-25 23:23
Because I want to use Browsh also without X-Server. (in pure Console-mode)

**Comment by tombh** [comment] 2022-02-25 23:30
Ohh GPM is a way of using the mouse without X11? I didn't know that. Yes I totally agree that Browsh should work in a pure console environment. So I'll mark this as a bug. Thank you

**Comment by tobi2409** [comment] 2022-02-25 23:30
Ohh GPM is a way of using the mouse without X11? Yes. Thank you :)

**Comment by tobi2409** [comment] 2022-02-26 12:53
Thank you :) And when we can plan with the bugfix? Because the latest version (1.64) is from 2019.

**Comment by tombh** [comment] 2022-02-26 13:30
The reality is that I neither need to find a way of making a living from Browsh or I need to save up enough money to be able to have the months I need to work on Browsh again. I would love to find a way, but it's not going to happen any time soon I'm afraid 😕

**Comment by 00c0** [comment] 2022-03-13 21:02
How can I implement it?

**Comment by tombh** [comment] 2022-03-13 21:37
First thing would be to set some debugging [here](https://github.com/browsh-org/browsh/blob/master/interfacer/src/browsh/tty.go#L173) to see if Browsh is even receiving events from GPM. Linux build instructions are here: https://github.com/browsh-org/browsh/blob/master/contrib/setup_linux_build_environment.md

**Comment by 00c0** [comment] 2022-03-14 20:29
Browsh isn't receiving events from GPM.

**Comment by tombh** [comment] 2022-03-14 22:18
Can you outline the steps you took to reproduce that?

**Comment by 00c0** [comment] 2022-03-14 22:43
I went into tty. I enabled the GPM service. I ran browsh with the --debug flag. I tried to click on links. I closed browsh. I looked at the log file.

**Comment by tombh** [comment] 2022-03-14 22:55
You didn't follow my instructions in the comment above: https://github.com/browsh-org/browsh/issues/402#issuecomment-1066187086

**Comment by 00c0** [comment] 2022-03-14 23:09
I'm sorry. I don't understand. Please may you explain.

**Comment by tombh** [comment] 2022-03-14 23:14
What don't you understand? Where the comment is? How to add code to Golang? How to build Browsh? You will need to experiment for yourself and let me know at what point you're unable to proceed any further.

**Comment by 00c0** [comment] 2022-03-15 02:20
I built browsh. I was able to use it in terminal on top of X. I was able to launch it in tty. I am unable to click in tty.

**Comment by tombh** [comment] 2022-03-15 10:51
Were you able to add a logging line here? https://github.com/browsh-org/browsh/blob/master/interfacer/src/browsh/tty.go#L173 If so, what is the logging line?

**Comment by 00c0** [comment] 2022-03-15 20:43
I was able to add a logging line there. The logging line is`Log("mouseEvent")`.

**Comment by tombh** [comment] 2022-03-15 20:59
Thanks, that's great. It led me to realise that it's a `tcell` issue. There's actually already an issue about it there! https://github.com/gdamore/tcell/issues/297 So you can discuss there if you'd like to implement the solution.

**Comment by tombh** [comment] 2022-03-15 21:00
So I'm going to close this issue as it is a duplicate of #237

**Closed** 2022-03-15 21:00 UTC
Labels: bug
