### ISSUE TITLE
No chinese fonts support.

### ISSUE THREAD

**Issue by netroby** [browsh-org/browsh#161] opened 2018-07-30 06:56 UTC
open one website contains chinese font. it not display well.

**Comment by trantata** [comment] 2018-07-30 07:14
Vào Th 2, 30 thg 7, 2018 lúc 13:56 netroby <notifications@github.com> đã
viết:

**Comment by tombh** [comment] 2018-07-30 13:30
Thanks for the report. This is a duplicate of #75

**Closed by tombh** 2018-07-30 13:30 UTC
