### ISSUE TITLE
windows10 error

### ISSUE THREAD

**Issue by zyp001a** [browsh-org/browsh#108] opened 2018-07-11 10:52 UTC
.\browsh_1.3.2_windows_amd64.exe
exec: "c:\\Program": file does not exist

**Comment by DanielRuf** [comment] 2018-07-11 11:00
It was probably deleted by Windows Defender. Please disable the realtime scanner as there are currently some AV scanners reporting a false positive.

**Comment by DanielRuf** [comment] 2018-07-11 11:01
See https://github.com/browsh-org/browsh/issues/67

**Comment by DanielRuf** [comment] 2018-07-11 11:02
> exec: "c:\Program": file does not exist

Also this seems more like you forgot to escape the space with `\` so you mea need `C:/Program\ Files\...`

**Comment by zyp001a** [comment] 2018-07-12 01:57
Windows Defender is off, I just download the .exe file and cannot execute, where escape the space with II Install firefox in another fold and use with -firefox, the error disappear but new error found
![image](https://user-images.githubusercontent.com/5070297/42608332-d6a72786-85b9-11e8-93bf-157eb930b088.png)

**Comment by DanielRuf** [comment] 2018-07-12 05:06
Looks like some memory issue. Does this always appear?

**Comment by zyp001a** [comment] 2018-07-12 09:42
Yes, every time I run it

**Comment by tombh** [comment] 2018-07-13 09:41
It looks like we have found a workaround. See #32, which is a duplicate of this problem.

**Closed by tombh** 2018-07-13 09:41 UTC
