### ISSUE TITLE
Feature request: Configuration file

### ISSUE THREAD

**Issue by tugcanolgun** [browsh-org/browsh#112] opened 2018-07-11 12:08 UTC
Hello,

As far as I know, there is no configuration file the settings of browsh. For starters, with this configuration file, key bindings can be rearranged. At the current state, I cannot typle any url because C^l is actually a tmux binding for me. Of course there are ways to get around that but still, a configuration file not only would give users to rebind the keys, but maybe other options as well.

I am going to suggest something. Instead of putting the configuration file to `~/.browsh` for example. Putting the configuration to `~/.config/browsh/` would be a better idea to seperate different config files. Examples: `~/.config/browsh/keybindings.conf` and `~/.config/browsh/colors.conf`

Thank you.

**Comment by tombh** [comment] 2018-07-13 08:56
This is a duplicate of #37 

I'm actually already using `~/.config/browsh/` for Browsh's Firefox profile, so it'll be easy to just place the config file there as well.

**Closed by tombh** 2018-07-13 08:56 UTC
