### ISSUE TITLE
dial tcp 127.0.0.1:2828: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by zz0rk** [browsh-org/browsh#117] opened 2018-07-11 16:48 UTC
dial tcp 127.0.0.1:2828: connectex: No connection could be made because the target machine actively refused it.

This is on Windows 10 Version 10.0.17134 Build 17134.
Is this a firewall issue?

**Comment by morrah** [comment] 2018-07-11 18:59
having the same issue.
it looks like the browsh doesn't wait for firefox to start and instantly printing this error, though when i open process list, there are firefox.exe processes.

it runs successfully using the `-use-existing-ff` flag

**Comment by zz0rk** [comment] 2018-07-11 20:44
Thanks for that tip.

**Comment by tombh** [comment] 2018-07-13 09:14
@morrah!!!!!! Are you saying you got Browsh to work on Windows!!?? If so then you are the first person I know to do so and you are going to make a lot of people happy :D 

I'm going to let the people in #32 know...

**Comment by tombh** [comment] 2018-07-15 13:34
Ok, well either way this is fantastic news. At the very least I can simply add a little sleep when starting Firefox on Windows as temporary workaround. But the main thing is that we now have a clear understanding of the underlying problem. Thanks so much!

**Comment by tombh** [comment] 2018-07-19 14:06
I confirmed the fix for this issue in v1.4.0 on my local machine. There may still be other Windows issues, which we can follow elsewhere or open new issues for.

**Closed by tombh** 2018-07-19 14:06 UTC
