### ISSUE TITLE
ASCII art rendering option

### ISSUE THREAD

**Issue by lukehutch** [browsh-org/browsh#104] opened 2018-07-10 23:17 UTC
Really cool project. Have you tried ASCII art rather than the Unicode block trick for graphics?

http://mir3z.github.io/aalib.js/

**Comment by tombh** [comment] 2018-07-13 08:37
When I very first started Texttop I did experiment a bit, but I must say I've not seen anything come close to the combination of true colour and UTF-8 half-block trick. Honestly, the only thing that I'd be open to is something like the 2x2 super resolution trick: https://github.com/blitzcode/term-gfx/blob/0f02606f62bf3adb9f5d92bb0fe13687f9f2aebe/src/main.rs#L58

**Comment by lukehutch** [comment] 2018-07-13 08:54
2x2 full-color blocks was going to be my other suggestion, I didn't know that someone had already done that. That doubles the horizontal resolution, but not the vertical resolution. It would still help a lot though.

Another possibility is to use something like an ASCII art algorithm, but instead use colored emoji characters, which are increasingly supported in consoles :-) It would be a really interesting experiment to see how well images could be represented with emoji, given the sheer number and variety of emoji characters in the latest Unicode releases.

**Comment by tombh** [comment] 2018-07-13 09:52
I've actually got another idea for a project, I'm dubbing it "tri-glyph cinema". So imagine using the full range of UTF-8 glyphs and all 16 million colours across just three side-by-side characters to play videos! 3 character seems to just about approximate 6:9 aspect ration. I'd use a GPU to find the best possible match for each frame using those the 3 characters. Of course it wouldn't be high res, but it could be quite a nice effect. I wonder if it'd be good enough to make certain famous movie scenes recognisable? And then once the GPU had done all its hard work, it'd be really easy to then load that into a webpage to be run in a gallery :)

**Comment by lukehutch** [comment] 2018-07-13 10:00
aalib.js can already do real-time black and white video with ASCII characters, it's amazing they can get this sort of performance out of JS: http://mir3z.github.io/aalib.js/examples/bbb.html
That library could be a good starting point.

**Comment by tobimensch** [comment] 2018-07-13 15:03
@tombh 
Did you think about using machine learning/deep learning for this?

There are algorythms for testing similarity between images.

So with deep learning and reinforcement learning, you might be able to train a neural network to find unicode characters to make the output image as similar as possible to the input.

Once that network is fully trained (let it compete with itself) it should be efficient at generating a near perfect unicode duplicate of an image.

**Comment by lukehutch** [comment] 2018-07-13 19:17
@tobimensch That seems like huge overkill! Fundamentally this is just a nearest neighbor problem over a comparatively very small domain.

**Comment by tombh** [comment] 2018-07-14 14:38
My "tri-glyph cinema" idea is something completely different from Browsh, but yeah it could certainly benefit from ML.

@lukehutch I still think the UTF-8 half-block trick with true colour has better rendering? Don't you? How does aalib.js handle colour? Because the half-block trick makes it very easy to decide on the BG/FG colour.

**Comment by lukehutch** [comment] 2018-07-15 04:04
@tombh I like the cleanness of how the half-block trick looks. But the resolution is pretty unusable, in my opinion.

Re. how aalib.js handles color -- see the site link, but they have different readers for video and image sources, then they average the color covered by a character: `colored:boolean - if true, the colors of the original image are preserved. Every character in a target image has a mean color of area it represents in the original image.`

**Comment by tombh** [comment] 2018-07-15 13:36
Thanks for that bit of documentation. So do you think that aalib.js can express more visual information per TTY cell from the source image than the UTF-8 half-block trick?

**Comment by lukehutch** [comment] 2018-07-15 19:51
For images and possibly logos, yes. It won't look as clean, but it might make the browser more functional. It should be pretty simple to try it to see.

**Comment by lukehutch** [comment] 2018-07-18 15:02
I'm not an expert on aalib.js, I just posted the link in case it was helpful. I don't know where to find a full-color example, but the API is simple enough that you could try it yourself with a few lines of html.

aalib.js is based on the ideas of aalib, the original native-code library had supports grayscale:

http://aa-project.sourceforge.net

A better library came out a few years later than aalib, libcaca, and you could link this into the Go code if you want:

http://caca.zoy.org/wiki/libcaca

There's also hiptext, which uses the half block trick:

https://github.com/jart/hiptext

**Comment by tombh** [comment] 2018-07-19 13:53
Browsh's previous incarnation (Texttop) actually used Hiptext, I even submitted a few PRs to it.

I made a relevant comment on this whole topic in another issue: https://github.com/browsh-org/browsh/issues/137#issuecomment-406282019

Basically I'm currently leaning towards not making any improvements to Browsh's graphics, other than the magnifying glass #33, because graphics improvements are always going to be merely subjective, whereas the magnifier will actually open up new abilities for Browsh, like answering captchas.

**Comment by lukehutch** [comment] 2018-07-19 15:54
Sure, feel free to close this if you don't have plans to change the graphics rendering.

**Comment by tombh** [comment] 2018-07-20 06:34
Ok thanks. Well I'm going to keep all the graphics discussion in #137

**Closed by tombh** 2018-07-20 06:34 UTC
Labels: duplicate, low priority, question
