### ISSUE TITLE
Panic runtime error invalid memory address or nil pointer [Debian x64]

### ISSUE THREAD

**Issue by smeggysmeg** [browsh-org/browsh#73] opened 2018-07-09 19:30 UTC
And that is not my user path. I don't know where that came from.

```
Starting Browsh, the modern text-based web browser.
Waiting for Firefox to connect...
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6dea06]

goroutine 11 [running]:

browsh/interfacer /src/browsh.handleMouseEvent(0xc4203259b0)

/home/travis/gopath/src/browsh/interfacer/src/browsh

/tty.go:151 +0x36 browsh/interfacer/src/browsh.readStdin() /home/travis/gopath/src/browsh/interfacer/src/browsh/tty.go:46 +0xd3 created by browsh/interfacer/src/browsh.TTYStart /home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:185 +0xf2
```

**Comment by forkbomb9** [comment] 2018-07-09 21:37
It happens to me too, ArchLinux up-to-date

**Comment by MrSrsen** [comment] 2018-07-09 21:45
#63 I was also getting errors on `handleMouseEvent` function. Possibly related?

**Comment by tombh** [comment] 2018-07-10 01:45
Yes, I think this is a duplicate of that #63 

@smeggysmeg and @forkbomb9 could you provide some output from the `./debug.log` file generated by `browsh -debug` please.

**Comment by forkbomb9** [comment] 2018-07-10 03:33
Reinstalled it, runned with `browsh -debug` and worked! Strange...

**Comment by smeggysmeg** [comment] 2018-07-10 03:57
Reinstall didn't solve it. Here is my debug log

[debug.log](https://github.com/browsh-org/browsh/files/2178771/debug.log)

**Comment by asymmetric** [comment] 2018-07-10 08:05
I have a different error in my [`debug.log`](https://github.com/browsh-org/browsh/files/2179397/debug.log): 

```
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,38,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 26:[1,39,null,{"value":null}]
Sending `addon:install` to Firefox Marionette
FF-CONSOLE: 1531209746310       addons.xpi      WARN    Invalid XPI: TypeError: aAddon._installLocation is undefined (resource://gre/modules/addons/XPIDatabase.jsm:1871:9) JS Stack trace: isUsableAddon@XPIDatabase.jsm:1871:9
FF-CONSOLE: updateBlocklistState@XPIDatabase.jsm:562:27
FF-MRNT: 347:[1,40,{"error":"unknown error","message":"Could not install add-on: /tmp/browsh-webext-addon963978470: ERROR_CORRUPT_FILE: The file appears to be corrupt.","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nUnknownError@chrome://marionette/content/error.js:483:5\ninstall@chrome://marionette/content/addon.js:103:13\n"},null]
Starting Browsh CLI client
Webextension not connected. Message not sent: /tty_size,191,50
```

**Comment by tombh** [comment] 2018-07-10 10:37
@smeggysmeg and @forkbomb9  both your logs look fine. @smeggysmeg can you just paste the error message that CLI returns at crash, just to confirm this is connected with the `handleMouseEvent` error, thanks.

@asymmetric woah! never seen that. Which Browsh binary are you using?

**Comment by smeggysmeg** [comment] 2018-07-10 13:18
Here's a different debug log, in case it reveals something different. 
[debug2.log](https://github.com/browsh-org/browsh/files/2180481/debug2.log)

Browsh never loads, it just keeps the loading screen there. I can confirm that the program crashes when I move my mouse over the terminal/ssh session, and after the crash every mouse movement over the terminal window causes text to be input.

Terminal I use is Guake.

**Comment by forkbomb9** [comment] 2018-07-10 17:09
@tombh at the end of the log there's a few lines with an error related to a path, and it's not my home, I run `browsh -debug` from /home/forkbomb, not /home/travis

**Comment by tombh** [comment] 2018-07-11 11:00
As of v1.3.2 this should be fixed. This version is also deployed to `ssh brow.sh`, so you should be able to test the fix there as well. Please let me know if you still have problems.

**Closed by tombh** 2018-07-11 11:00 UTC
Labels: duplicate

**Comment by kerberoid** [comment] 2023-09-01 20:36
Hi, looking at this issue I see it's been a while.
I have the exact same issue in version 1.8.0 under ARM64 Ubuntu.
The docker runs, but really slow. so I want to try an Install on the machine itself.

**Comment by Xses-1** [comment] 2023-09-03 20:31
I have an issue that gives the same terminal output, but nothing in the debug log.

**Comment by liyiyuian** [comment] 2023-09-24 19:02
Hi, I also have the same terminal output. The version I installed was 1.8.2.

**Comment by darsiov** [comment] 2023-11-20 06:51
@liyiyuian  me too, i have te same version and I'm using ubuntu 22.04

**Comment by luislve17** [comment] 2024-09-08 21:03
Any news about this?

**Comment by Xses-1** [comment] 2024-09-09 05:39
@luislve17 I was using non-snap Firefox for sure. I will check other dependencies and what happens.
