### ISSUE TITLE
HTTPS Pages with self-signed SSL sites (router, NAS) lead to empty page stucked at "Loading…"

### ISSUE THREAD

**Issue by bentolor** [browsh-org/browsh#183] opened 2018-08-20 09:20 UTC
I'm trying to access the NAS admin UI which redirects to the SSL-encrypted version using a self-signed certificate.

In native Firefox as a user you get confronted with a Firefox "error page" about the insecure page and options to continue & accepts the unknown CA anyways.

In browsh accessing URLs which are or redirect to SSL-locations with a self-signed CA let browsh appear to be stucked and does not show any reaction.

I'm on Ubuntu 16.04, Firefox 61.0.1, installed browsh via 64-bit deb.

**Comment by tobimensch** [comment] 2018-08-20 11:09
I think this is a duplicate of #127.

**Closed by tobimensch** 2018-08-20 11:09 UTC
Labels: duplicate
