### ISSUE TITLE
No mouse support inside tmux over mosh

### ISSUE THREAD

**Issue by daniellandau** [browsh-org/browsh#160] opened 2018-07-30 05:52 UTC
On Ubuntu 16.04 with gnome-terminal I can ssh to a host and use browsh normally, but over mosh (git head at 60859e9d090f530022ffc3e1345975bfdd1b3978 on both client and server) mouse just selects text from the terminal window.

Using browsh version 1.4.10 from the .deb downloaded from Github, but would be happy to test any other version if that helps.

**Comment by jxyzn** [comment] 2018-08-07 19:55
Just noting that I'm able to use mouse navigation with gnome-terminal and new mosh (from the dev-test ppa) on 16.04, so some deep config option someplace?

**Comment by daniellandau** [comment] 2018-08-12 08:40
The log: [debug.log](https://github.com/browsh-org/browsh/files/2280828/debug.log)

It seems to actually be browsh inside mosh inside *tmux* that is the problem, not the terminal emulator used.

Works: browsh inside tmux
Works: browsh inside ssh inside tmux
Doesn't work: browsh inside mosh inside tmux

```sh
% tmux -V
tmux 2.1
```

My tmux shouldn't be configured to capture the mouse.

**Comment by jxyzn** [comment] 2018-08-12 18:37
Heh. I knew there was a good reason I've avoided tmux! ;) I successfully use browsh with the mouse via mosh to a doubly-nested 'screen' session!

**Comment by tombh** [comment] 2018-08-19 11:02
Ok, I've updated the title to be more specific. I have no idea how to start debugging this!

**Comment by j-rewerts** [comment] 2018-08-21 04:17
I actually use tmux with Browsh all the time. I've tested the following:
Browsh in Terminal
Browsh in Terminal in tmux

Both seem to work for me!

**Comment by hevanaa** [comment] 2019-02-06 14:07
No mouse support inside tmux over ssh for me (Fedora 29).
Mouse works over ssh (without tmux).

**Comment by j-rewerts** [comment] 2019-02-06 16:53
@hevanaa How are you running Browsh? `ssh brow.sh`?

**Comment by hevanaa** [comment] 2019-02-06 16:59
I was using a Win 10 PC with Putty and opened a remote SSH session to a Linux PC (Fedora 29) that had tmux and browsh installed. I think Windows/Putty was the problem. Because now I'm on a Linux PC (Fedora 29) with a remote SSH session to another Linux PC (Fedora 29) that has tmux and browsh installed, and it is working perfectly fine, both in plain terminal and using tmux.

**Comment by j-rewerts** [comment] 2019-02-06 17:51
So just to summarize, it seems like there are issues with mouse scrolling on 2 confirmed setups:
 - PuTTY connected to Fedora
 - Mosh/TMux

**Comment by j-rewerts** [comment] 2019-02-06 17:52
@daniellandau Could you confirm how you're connecting to Browsh? Are you running it in a Docker container?

**Comment by hevanaa** [comment] 2019-02-06 18:17
I would rather say one minor problem is:
- Putty connected to Fedora with browsh inside a tmux session (without tmux it worked it worked fine within the remote bash shell).

I'm not using Docker. What do you exactly mean by "connecting to Browsh"? That's a concept I'm not familiar with. I've installed the rpm in linux and starting it from the command line with 'browsh' i.e. /usr/local/bin/browsh.

**Comment by j-rewerts** [comment] 2019-02-06 18:25
There are a few different ways to use Browsh. 
 - You could run the package, like you have. 
 - You could run a Docker container.
 - You could just run `ssh brow.sh`

**Comment by daniellandau** [comment] 2019-02-06 19:32
I've since updated to Ubuntu 18.10, and just updated to Mosh 1.5. The issue is now gone for me and mouse works as expected.

**Comment by tobimensch** [comment] 2019-02-07 07:00
Since this issue got fixed for the person who originally opened it and seems very likely the issue does have nothing to do with Browsh itself, but rather different versions of terminals, tmux and Mosh having interoperability issues, I want to close this issue.

If you're still having issues, try to update all of the software mentioned above to the latest version. See if you can get to run other terminals than Putty on Windows. If all of that doesn't help, open an issue at the issue tracker of your terminal, which is the most likely culprit, as the latest versions of Mosh/tmux are known to work.

**Closed by tobimensch** 2019-02-07 07:00 UTC
Labels: bug
