### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference [Windows 10]

### ISSUE THREAD

**Issue by niutech** [browsh-org/browsh#68] opened 2018-07-09 13:14 UTC
When I run `browsh_1.2.2_windows_amd64.exe` on Windows 10 x64, Firefox opens, but the program crashes with:

> panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4b4cdd]
> goroutine 6 [running]: 
> os.(*Process).signal(0x0, 0x7cd560, 0x91c3c8, 0xc04229a070, 0x0)

**Comment by tombh** [comment] 2018-07-09 13:53
This is a duplicate of #38

**Closed by tombh** 2018-07-09 13:53 UTC
Labels: duplicate

**Comment by niutech** [comment] 2018-07-09 14:35
Is it really _#38 In-browser help_?

**Comment by mholt** [comment] 2018-07-09 17:06
This is definitely NOT a duplicate of #38. I'm getting the error too on Fedora, with the same binary.

**Comment by smeggysmeg** [comment] 2018-07-09 19:09
I'm getting the same problem on both Debian and Fedora.

**Comment by niutech** [comment] 2018-07-10 09:15
Full stack:

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x8 pc=0x4b4cdd]
> 
> goroutine 6 [running]:
> os.(*Process).signal(0x0, 0x7d2540, 0x9233c8, 0xc0421a6070, 0x0)
> 	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_windows.go:58 +0x2d
> os.(*Process).Signal(0x0, 0x7d2540, 0x9233c8, 0xc042193e90, 0x18)
> 	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:129 +0x46
> os.(*Process).kill(0x0, 0xc042036c28, 0xc042193e90)
> 	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_posix.go:54 +0x4a
> os.(*Process).Kill(0x0, 0x4, 0x4)
> 	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:114 +0x32
> browsh/interfacer/src/browsh.startHeadlessFirefox()
> 	/home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:84 +0x36c
> created by browsh/interfacer/src/browsh.setupFirefox
> 	/home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:252 +0x3c

**Comment by tombh** [comment] 2018-07-10 10:23
OMG! I'm so sorry. I meant #32!

**Comment by mholt** [comment] 2018-07-10 11:47
Ah! :) That's more like it, thanks.

**Comment by kishor-p** [comment] 2019-09-16 10:50
> 
> 
> Full stack:
> 
> > panic: runtime error: invalid memory address or nil pointer dereference
> > [signal 0xc0000005 code=0x0 addr=0x8 pc=0x4b4cdd]
> > goroutine 6 [running]:
> > os.(*Process).signal(0x0, 0x7d2540, 0x9233c8, 0xc0421a6070, 0x0)
> > /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_windows.go:58 +0x2d
> > os.(*Process).Signal(0x0, 0x7d2540, 0x9233c8, 0xc042193e90, 0x18)
> > /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:129 +0x46
> > os.(*Process).kill(0x0, 0xc042036c28, 0xc042193e90)
> > /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_posix.go:54 +0x4a
> > os.(*Process).Kill(0x0, 0x4, 0x4)
> > /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:114 +0x32
> > browsh/interfacer/src/browsh.startHeadlessFirefox()
> > /home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:84 +0x36c
> > created by browsh/interfacer/src/browsh.setupFirefox
> > /home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:252 +0x3c
> 
> Why is there `/home/travis/` when it is run on Windows?

Did you ever solve this I get same error on Windows7 Docker Tollbox
