### ISSUE TITLE
64 bit Firefox not found on Windows

### ISSUE THREAD

**Issue by dbenzhuser** [browsh-org/browsh#87] opened 2018-07-10 11:57 UTC
In src/browsh/firefox.go, the path to the Firefox executable is fixed to
`c:\Program Files (x86)\Mozilla Firefox\firefox.exe`
The 64 bit version of Firefox is (usually) located at
`c:\Program Files\Mozilla Firefox\firefox.exe`

I couldn't find any hint in the documentation stating that 32 bit Firefox was required.

**Comment by joelhandwell** [comment] 2018-07-10 12:49
browsh can try to find 64bit version as default location and if it's not found it can try to find 32 bit version which is installed in C:\C:\Program Files (x86)\Mozilla Firefox\firefox.exe

**Comment by Duroktar** [comment] 2018-07-10 18:45
I'm experiencing the same issue as @dbenzhuser and #89 & #91 ... It looks like the problem is here: https://github.com/browsh-org/browsh/blob/master/interfacer/src/browsh/firefox.go#L99 . I'm getting a PR together now because I honestly can't wait to try this out :)

**Comment by janmechtel** [comment] 2018-07-10 19:04
somebody mentioned elsewhere there is a -ff or -f option, I haven't tried it. Instead I've created a symbolic link with

` mklink \J "C:\Program Files\Mozilla Firefox" "C:\Program Files(x86)\Mozilla Firefox"`

**Comment by Duroktar** [comment] 2018-07-10 19:15
@janmechtel That's stellar, thanks!

**Comment by Rav3nPL** [comment] 2018-07-10 19:39
No go on win10x64
Firefox is starting and whats below sits in screen
`````
panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4b4cdd]


goroutine 19 [running]:

(0x0, 0x7d2540, , 0

Y @@@
@ @@@
@@@@@
Starting Browsh, the modern text-based web browser.
Waiting for Firefox to connect...

```

**Comment by Duroktar** [comment] 2018-07-10 19:54
I have the same error as @Rav3nPL on Windows 7. Looks like this is probably gonna end up being a separate issue..

**Comment by egryaznov** [comment] 2018-07-11 09:08
Same issue as @Rav3nPL here on Win10 x64 with Firefox 61.0.1 (64 bit)

**Comment by tombh** [comment] 2018-07-13 08:48
I've had to mark the Windows binary as experimental on the downloads page: https://www.brow.sh/downloads/ As I've not been able to find a fix to the underlying problems on Windows :(

Although some fixes have been added to deal with the Firefox path. There still remains the dreaded "dial tcp 127.0.0.1:2828: connectex: No connection could be made" error, which I have no idea about. So I'm going to close this issue in favour of where that error was first reported: #32

**Closed by tombh** 2018-07-13 08:48 UTC
