### ISSUE TITLE
Add support for AltGr letters

### ISSUE THREAD

**Issue by osowiecki** [browsh-org/browsh#81] opened 2018-07-10 06:35 UTC
AltGr doesn't seem to work properly. On Google you get pic related.
On facebook it doesn't work at all.
I'm testing on Konsole which supports these characters.

https://s33.postimg.cc/439c8ehq7/Selection_092.png

**Comment by tombh** [comment] 2018-07-10 10:28
I'm not familiar with what the AltGr key should do.

When running `browsh -debug` do you see the expected keys logged in `./debug.log`?

**Comment by osowiecki** [comment] 2018-07-10 10:48
AltGr lets you input non-english letters for example into google.
"zażółć gęślą jaźń"

**Comment by tombh** [comment] 2018-07-13 08:03
Ah yes, of course, I did actually know that about AltGr. And now I can exactly reproduce the problem on my terminal. Also, when I'm out of Browsh on my ZSH prompt AltGr keys work perfectly So this is a definite bug. Thanks for reporting.

**Comment by tombh** [comment] 2018-07-13 08:21
Closing this in favour of #93, just because it seems to have a more relevant title. This is more to do with UTF-8 in general, than AltGr specifically.

**Closed** 2018-07-13 08:22 UTC
Labels: bug
