### ISSUE TITLE
ver 1.3.3 error tcp:3334 already in use

### ISSUE THREAD

**Issue by osmand** [browsh-org/browsh#124] opened 2018-07-12 09:00 UTC
when running 2nd time after 5 minute session I got this error

listen tcp :3334: bind: address already in use
panic: interface conversion: error is *net.OpError, not *errors.Error

goroutine 1 [running]:
browsh/interfacer/src/browsh.Shutdown(0x7d8c00, 0xc42021bdb0)
	/home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:114 +0x195
browsh/interfacer/src/browsh.startWebSocketServer()
	/home/travis/gopath/src/browsh/interfacer/src/browsh/comms.go:31 +0xf4
browsh/interfacer/src/browsh.TTYStart(0x7de340, 0xc420098b60)
	/home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:176 +0xf7
browsh/interfacer/src/browsh.ttyEntry()
	/home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:208 +0x100
browsh/interfacer/src/browsh.MainEntry()
	/home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:217 +0x41
main.main()
	/home/travis/gopath/src/browsh/interfacer/src/main.go:6 +0x20
Connection to brow.sh closed.

**Comment by joereynolds** [comment] 2018-07-12 09:09
That doesn't look like anything to do with browsh.

You'll need to run

(You might need `sudo`)
```
lsof -i :3334
```

and find out what is hogging that port.

**Comment by tombh** [comment] 2018-07-13 09:38
This sounds like Browsh itself didn't shut down properly. Maybe try `killall browsh`.

**Comment by tombh** [comment] 2018-07-19 14:10
Oh this is a problem with the live SSH demo. That was just probably caused by a unhappy Docker instance. Whereas this may well indicate a real bug, it is much more likely a bug with https://github.com/browsh-org/baas So I'm going to close it here, but we can revisit it if more errors are reported.

**Closed by tombh** 2018-07-19 14:10 UTC
