### ISSUE TITLE
dial tcp connectex: No connection could be made ... - panic: interface connection

### ISSUE THREAD

**Issue by vlastimilmaca** [browsh-org/browsh#78] opened 2018-07-10 05:16 UTC
Hi. This happens on Windows with v1.2.3:

dial tcp 127.0.0.1:2828: connectex: No connection could be made because the target machine actively refused it
panic: interface conversion: error is *net.OpError, not *errors.Error

goroutine 1 [running]:
browsh/interfacer/src/browsh.Shutdown(0x7cf640, 0xc0421ce1e0)
        /home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:115 +0x19c
browsh/interfacer/src/browsh.firefoxMarionette()
        /home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:166 +0x195
browsh/interfacer/src/browsh.setupFirefox()
        /home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:256 +0x50
browsh/interfacer/src/browsh.startFirefox()
        /home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:268 +0x109
browsh/interfacer/src/browsh.TTYStart(0x7d4ba0, 0xc042160000)
        /home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:183 +0xc8
browsh/interfacer/src/browsh.ttyEntry()
        /home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:218 +0xd9
browsh/interfacer/src/browsh.MainEntry()
        /home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:227 +0x48
main.main()
        /home/travis/gopath/src/browsh/interfacer/src/main.go:6 +0x27

Am I doing anything wrong?

**Comment by tombh** [comment] 2018-07-10 10:21
This is a duplicate of #32

**Closed by tombh** 2018-07-10 10:21 UTC
Labels: duplicate

**Comment by Aidoboy** [comment] 2018-07-13 11:46
@tombh I don't know if this should necessarily be closed, automatically finding Firefox is still broken, and you have to know about the `~` path workaround, because the path can't have any spaces in it, even with quotes.
