### ISSUE TITLE
PDF Viewer: Feature Request

### ISSUE THREAD

**Issue by prairie-guy** [browsh-org/browsh#427] opened 2022-07-09 17:56 UTC
My objective is to read `pdf` files from my iPad hosted on other machines. When I use `browsh` from the terminal on Ubuntu and I select a `pdf` link, it launches a `pdf viewer`. When I do the same logged in with `Blink.sh` from my iPad to Ubuntu 22.04, nothing happens. Since `Firefox` is able to view `pdf` docs natively, I had hopped I could do the same with `browsh`. Perhaps there is a way that I have missed, in which case, please let me know. Otherwise, this would be a very nice feature for `browsh`

Very nice program. Exactly what I need to be able to do simple browsing from when logged in to a remote network.

**Comment by tombh** [comment] 2022-07-16 01:40
Yes, this is definitely something I want Browsh to be able to do!

Duplicate of #327.

**Closed by tombh** 2022-07-16 01:40 UTC
Labels: duplicate
