### ISSUE TITLE
Loopback address support

### ISSUE THREAD

**Issue by drumwhizz** [browsh-org/browsh#456] opened 2023-01-16 16:57 UTC
Love this browser. One thing I have discovered that is holding me back is the use of the loopback interface as a URL.

If I type in the URL http://localhost:8000/ (my local web UI) it just sits there and does nothing, it doesn't even say loading...
If I type in the URL http://127.0.0.1:8000/ it does say loading but just hangs and ends up with a "Problem Loading Page" error.

I am running browsh on an Dell Edge 3000 IOT Gateway (Ubuntu 18.04 latest) and have ssh'd into a bash terminal on that machine in order to access the local web UI.

How do I pass the "--debug" argument into the docker container?

**Comment by drumwhizz** [comment] 2023-01-16 17:04
I will add those loopback URLs were working on the same machine when using wget from the bash terminal.

**Comment by tombh** [comment] 2023-01-27 13:27
This has been a long-standing issue 😞

So closing this for https://github.com/browsh-org/browsh/issues/76

**Closed by tombh** 2023-01-27 13:27 UTC

**Comment by adamency** [comment] 2024-02-15 11:00
@drumwhizz (cc @tombh) Just wanted to point out that this problem is most likely caused by the fact that you're launching `browsh` inside a container rather than directly on your host. I had the same problem but it was because I used the docker container. When launching the program directly on my machine, both addresses work perfectly.
