### ISSUE TITLE
Safari shows a warning when opening the website

### ISSUE THREAD

**Issue by IonicaBizau** [browsh-org/browsh#58] opened 2018-07-09 07:34 UTC
![screen shot 2018-07-09 at 10 33 59](https://user-images.githubusercontent.com/2864371/42436727-a87da05e-8363-11e8-8721-03ead77023e3.png)

**Comment by tombh** [comment] 2018-07-09 07:40
This is caused by the fact that the live HTML service can render sites like: https://html.brow.sh/http://mail.google.com  Google then detects that as an attempt to phish Gmail user's usernames  and passwords. The HTML service only returns plain text, <pre> & <a> tags, not even any JS. So it's actually impossible for a phishing attack to occur. I've disabled the HTML services ability to parse Gmail now and  submitted a review to Google a few hours ago. But Google said it could  take up to 72 hours :/

**Comment by tombh** [comment] 2018-07-09 08:28
:''''''(

**Comment by DanielRuf** [comment] 2018-07-09 10:51
3 left =)
Should be propagating very fast. If not let me know, I have maybe still some contacts from the past which I can write to update faster or immediately add the website to the whitelist.

https://www.virustotal.com/#/url/54ab74be93601eb2f252364829ce5a61a8840f52c0f4cfe7a09f0c32730b8c85/detection

**Comment by tombh** [comment] 2018-07-09 10:56
Woohoo! :man_dancing:

Wow, thanks, ok, I'll keep an eye on it.

**Comment by DanielRuf** [comment] 2018-07-09 10:58
Reanalyzing it from time to time should hopefully show all green in about a few hours.

![bildschirmfoto 2018-07-09 um 12 57 25](https://user-images.githubusercontent.com/827205/42446754-b7b90270-8377-11e8-85b3-763708cea2c2.png)

**Comment by IonicaBizau** [comment] 2018-07-09 10:58
Thanks for the quick feedback and actions! 👍 I didn't know `virustotal.com`—it seems a handy tool.

And, hey! Congrats for the project! Few months ago I wanted to do the same with Electron, but I gave up because I couldn't find/create a good CLI renderer. 😂 

It's so nice to see this project alive and it made my day! 😁 
Keep up the great work! 🚀

**Comment by DanielRuf** [comment] 2018-07-09 10:59
And here is also a list of the contacts for reporting false positives: https://www.techsupportalert.com/content/how-report-malware-or-false-positives-multiple-antivirus-vendors.htm

**Comment by DanielRuf** [comment] 2018-07-09 11:00
> I didn't know virustotal.com

It's quite old, a great platform for us who are interested in security and malware analysis and so on and was bought by Google a few years ago. They finally published the resigned website this year =)

**Comment by DanielRuf** [comment] 2018-07-09 11:01
> It's so nice to see this project alive and it made my day! 😁
> Keep up the great work! 🚀

Definitely =) 👍

**Comment by DanielRuf** [comment] 2018-07-09 11:02
Almost 5 years there =) https://www.virustotal.com/#/user/DanielRuf

**Comment by DanielRuf** [comment] 2018-07-09 13:07
2 left https://www.virustotal.com/#/url/54ab74be93601eb2f252364829ce5a61a8840f52c0f4cfe7a09f0c32730b8c85/detection

**Comment by tombh** [comment] 2018-07-09 13:43
Woohoo! Getting there :)

**Comment by DanielRuf** [comment] 2018-07-09 15:33
I guess it needs some more time to propagate, another AV vendor blacklisted it too.

https://www.virustotal.com/#/url/54ab74be93601eb2f252364829ce5a61a8840f52c0f4cfe7a09f0c32730b8c85/detection

I guess I'll contact them later.

**Comment by DanielRuf** [comment] 2018-07-09 20:15
AegisLab and BitDefender
https://www.virustotal.com/#/url/54ab74be93601eb2f252364829ce5a61a8840f52c0f4cfe7a09f0c32730b8c85/detection

**Comment by tombh** [comment] 2018-07-10 01:09
Yeah still on 2. So do you reckon they have their own detection systems or are just piggybacking off the old Google Safe Browsing report?

**Comment by DanielRuf** [comment] 2018-07-10 05:09
In most cases they are subscribers of Google Safebrowsing and just need some time to sync. I'll contact them in about 1 - 2 hours.

**Comment by tombh** [comment] 2018-07-10 10:38
Thanks so much for @DanielRuf for helping out with this!

**Comment by DanielRuf** [comment] 2018-07-11 11:04
Still the same =/

https://www.virustotal.com/#/url/54ab74be93601eb2f252364829ce5a61a8840f52c0f4cfe7a09f0c32730b8c85/detection

I guess I have to escalate this at the AV vendors (today).

**Comment by tombh** [comment] 2018-07-11 11:07
Thanks so much for keeping on top of this @DanielRuf!

**Comment by tombh** [comment] 2018-07-12 04:53
They've all gone green! https://www.virustotal.com/#/url/54ab74be93601eb2f252364829ce5a61a8840f52c0f4cfe7a09f0c32730b8c85/detection

All thanks to @DanielRuf :D

**Comment by DanielRuf** [comment] 2018-07-12 05:41
Awesome =)

If there is anything popping up again, just let me know and I check what we can do then.

**Comment by tombh** [comment] 2018-07-13 09:21
AWESOME =) Thank you!

Ok, so I can finally close this :)

**Closed by tombh** 2018-07-13 09:21 UTC

**Comment by IonicaBizau** [comment] 2018-07-13 09:36
🎉
