### ISSUE TITLE
Cannot Login to certain web interfaces

### ISSUE THREAD

**Issue by tmanok** [browsh-org/browsh#397] opened 2022-01-13 07:26 UTC
Hi All,

While trying desperately to connect to a TrueNAS machine that is physically not accessible to me, I resorted to trying every method I could come up with, including SSH forwarding, Links, Lynx, w3m, and even Browsh! Browsh was the most promising, however it cannot complete a login. For whatever reason, Browsh misinterperates the login prompt on TrueNAS in such a way that it ALMOST works but introduces other characters into the fields. I attempted on multiple other TrueNAS machines locally and this was also the case. (Known good passwords for all of these machines, including the remote machine). 

If anyone on the Dev team would like to test browsh on a TrueNAS box and resolve the problem for future compatibility, that would be stellar. This may also fix other login prompts. Here's a screenshot for good measure, but it is only available temporarily (1month): https://ibb.co/pRPZN4p and the version of Browsh in use: 1.6.4 on Debian Bullseye with Firefox ESR 91.4.1esr. If you want me to export the source code for the TrueNAS login page or retrieve it on GitHub, I'm certain that I could figure that out to support this process. 

Note that the screenshot also shows that I am using Proxmox Backup Server as a Shell, however this was also the case in Guake, Gnome Terminal, and the console of a LinuxMint 20.3 machine. Fantastically, the PBS Shell also allows me to use the cursor with Browsh, congrats to both Proxmox Dev Team and Browsh for building tools that seamlessly work together, especially as a systems engineer. 
Thanks,

Tmanok

**Comment by tombh** [comment] 2022-01-13 23:38
I've seen this myself, see #336 (actually I'm going to mark this issue as a duplicate of that one) and it's quite unfortunate that such a small bug has such a big impact. Unfortunately there isn't a Browsh team, it's just me, and it's hard to focus on Browsh when it doesn't generate much earnings 😕 I have a plan for an almost complete rewrite, I'm hoping to get to it this year.

**Closed by tombh** 2022-01-13 23:38 UTC
